num1 = int(input("your first number:"))
num2 = int(input("your second number:"))
num3 = int(input("your third number:"))
print(num1 * num2 + num3)
print(num2 / num3 - num1)
print(num1 - num2 + num3)
print(num2 + num1 / num3)
print(num1 + num3 + num2)
print(num1 * num2 * num3)
print(num1 + num3 * num2)
print(num2 * (-num1) * num3)
print(num2 + num1 / num3)
print(num1 + num1 + num2 - num3)
print(num1 * num1 - num2 / num3)
print(num1 / num1 * num2 - num3)
print(num1 - num1 - num2 + num3)
print(num1 + num1 / num2 - num3)