a = float(input())
b = float(input())
print(a + b)
c = str(input())
d = str(input())
print(c + d)
e = int(input("your age:"))
print(e + 10)
f = int(input())
g = int(input())
print(f + g)
print(0 > 1)
print(2 > 1)
print(3 > 1)
print(0 > 1)
print(2 > 1)
print(3 > 1)
print(4 > 1)
print(7 > 1)
print(9 > 1)
print(4 > 1)
print(5 > 1)
print(True and False)
print(False and False)
print(True and False)
print(False and False)
print(True and False)
print(False or False)
print(True or False)
print(False or False)
print(True or False)
print(False or False)
print(0 > 1 and 1 < 0)
print(9 > 2 and 2 < 9)
print(8 > 3 and 3 < 8)
print(7 > 4 and 4 < 7)
print(6 > 5 and 5 < 6)
print(5 > 6 and 6 < 5)
print(4 > 7 and 7 < 4)
print(3 > 8 and 8 < 3)
print(2 > 9 and 9 < 2)
print(1 > 0 and 0 < 1)
# pseudocode is a description of the steps in an algorithm using a mix of conventions of programming languages
# selection is a option that anyone chooses,like we choose what to buy in grocery store